// src/core/configurations/country/CountryRegion.ts

export interface CountryConfig {
  code: string; // ISO alpha-2
  name: string; // English country name
  nativeName?: string;
  currencyCode: string; // ISO 4217
  currencySymbol: string;
  currencyName: string;
  phoneCode: string; // International dialing code
  locale: string; // sensible default locale
  flag: string; // Unicode flag emoji
  isActive: boolean;
}

export const COUNTRIES: Record<string, CountryConfig> = {
  AF: {
    code: 'AF',
    name: 'Afghanistan',
    nativeName: 'افغانستان',
    currencyCode: 'AFN',
    currencySymbol: '؋',
    currencyName: 'Afghan Afghani',
    phoneCode: '+93',
    locale: 'ps-AF',
    flag: '🇦🇫',
    isActive: true,
  },
  AL: {
    code: 'AL',
    name: 'Albania',
    nativeName: 'Shqipëria',
    currencyCode: 'ALL',
    currencySymbol: 'L',
    currencyName: 'Albanian Lek',
    phoneCode: '+355',
    locale: 'sq-AL',
    flag: '🇦🇱',
    isActive: true,
  },
  DZ: {
    code: 'DZ',
    name: 'Algeria',
    nativeName: 'الجزائر',
    currencyCode: 'DZD',
    currencySymbol: 'د.ج',
    currencyName: 'Algerian Dinar',
    phoneCode: '+213',
    locale: 'ar-DZ',
    flag: '🇩🇿',
    isActive: true,
  },
  AD: {
    code: 'AD',
    name: 'Andorra',
    nativeName: 'Andorra',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+376',
    locale: 'ca-AD',
    flag: '🇦🇩',
    isActive: true,
  },
  AO: {
    code: 'AO',
    name: 'Angola',
    nativeName: 'Angola',
    currencyCode: 'AOA',
    currencySymbol: 'Kz',
    currencyName: 'Angolan Kwanza',
    phoneCode: '+244',
    locale: 'pt-AO',
    flag: '🇦🇴',
    isActive: true,
  },
  AG: {
    code: 'AG',
    name: 'Antigua and Barbuda',
    nativeName: 'Antigua and Barbuda',
    currencyCode: 'XCD',
    currencySymbol: '$',
    currencyName: 'East Caribbean Dollar',
    phoneCode: '+1268',
    locale: 'en-AG',
    flag: '🇦🇬',
    isActive: true,
  },
  AR: {
    code: 'AR',
    name: 'Argentina',
    nativeName: 'Argentina',
    currencyCode: 'ARS',
    currencySymbol: '$',
    currencyName: 'Argentine Peso',
    phoneCode: '+54',
    locale: 'es-AR',
    flag: '🇦🇷',
    isActive: true,
  },
  AM: {
    code: 'AM',
    name: 'Armenia',
    nativeName: 'Հայաստան',
    currencyCode: 'AMD',
    currencySymbol: '֏',
    currencyName: 'Armenian Dram',
    phoneCode: '+374',
    locale: 'hy-AM',
    flag: '🇦🇲',
    isActive: true,
  },
  AU: {
    code: 'AU',
    name: 'Australia',
    nativeName: 'Australia',
    currencyCode: 'AUD',
    currencySymbol: '$',
    currencyName: 'Australian Dollar',
    phoneCode: '+61',
    locale: 'en-AU',
    flag: '🇦🇺',
    isActive: true,
  },
  AT: {
    code: 'AT',
    name: 'Austria',
    nativeName: 'Österreich',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+43',
    locale: 'de-AT',
    flag: '🇦🇹',
    isActive: true,
  },
  AZ: {
    code: 'AZ',
    name: 'Azerbaijan',
    nativeName: 'Azərbaycan',
    currencyCode: 'AZN',
    currencySymbol: '₼',
    currencyName: 'Azerbaijani Manat',
    phoneCode: '+994',
    locale: 'az-AZ',
    flag: '🇦🇿',
    isActive: true,
  },
  BS: {
    code: 'BS',
    name: 'Bahamas',
    nativeName: 'Bahamas',
    currencyCode: 'BSD',
    currencySymbol: '$',
    currencyName: 'Bahamian Dollar',
    phoneCode: '+1242',
    locale: 'en-BS',
    flag: '🇧🇸',
    isActive: true,
  },
  BH: {
    code: 'BH',
    name: 'Bahrain',
    nativeName: 'البحرين',
    currencyCode: 'BHD',
    currencySymbol: 'ب.د',
    currencyName: 'Bahraini Dinar',
    phoneCode: '+973',
    locale: 'ar-BH',
    flag: '🇧🇭',
    isActive: true,
  },
  BD: {
    code: 'BD',
    name: 'Bangladesh',
    nativeName: 'বাংলাদেশ',
    currencyCode: 'BDT',
    currencySymbol: '৳',
    currencyName: 'Bangladeshi Taka',
    phoneCode: '+880',
    locale: 'bn-BD',
    flag: '🇧🇩',
    isActive: true,
  },
  BB: {
    code: 'BB',
    name: 'Barbados',
    nativeName: 'Barbados',
    currencyCode: 'BBD',
    currencySymbol: '$',
    currencyName: 'Barbadian Dollar',
    phoneCode: '+1246',
    locale: 'en-BB',
    flag: '🇧🇧',
    isActive: true,
  },
  BY: {
    code: 'BY',
    name: 'Belarus',
    nativeName: 'Беларусь',
    currencyCode: 'BYN',
    currencySymbol: 'Br',
    currencyName: 'Belarusian Ruble',
    phoneCode: '+375',
    locale: 'be-BY',
    flag: '🇧🇾',
    isActive: true,
  },
  BE: {
    code: 'BE',
    name: 'Belgium',
    nativeName: 'België',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+32',
    locale: 'nl-BE',
    flag: '🇧🇪',
    isActive: true,
  },
  BZ: {
    code: 'BZ',
    name: 'Belize',
    nativeName: 'Belize',
    currencyCode: 'BZD',
    currencySymbol: '$',
    currencyName: 'Belize Dollar',
    phoneCode: '+501',
    locale: 'en-BZ',
    flag: '🇧🇿',
    isActive: true,
  },
  BJ: {
    code: 'BJ',
    name: 'Benin',
    nativeName: 'Bénin',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+229',
    locale: 'fr-BJ',
    flag: '🇧🇯',
    isActive: true,
  },
  BT: {
    code: 'BT',
    name: 'Bhutan',
    nativeName: 'འབྲུག',
    currencyCode: 'BTN',
    currencySymbol: 'Nu.',
    currencyName: 'Bhutanese Ngultrum',
    phoneCode: '+975',
    locale: 'dz-BT',
    flag: '🇧🇹',
    isActive: true,
  },
  BO: {
    code: 'BO',
    name: 'Bolivia',
    nativeName: 'Bolivia',
    currencyCode: 'BOB',
    currencySymbol: 'Bs.',
    currencyName: 'Bolivian Boliviano',
    phoneCode: '+591',
    locale: 'es-BO',
    flag: '🇧🇴',
    isActive: true,
  },
  BA: {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    nativeName: 'Bosna i Hercegovina',
    currencyCode: 'BAM',
    currencySymbol: 'KM',
    currencyName: 'Bosnia-Herzegovina Convertible Mark',
    phoneCode: '+387',
    locale: 'bs-BA',
    flag: '🇧🇦',
    isActive: true,
  },
  BW: {
    code: 'BW',
    name: 'Botswana',
    nativeName: 'Botswana',
    currencyCode: 'BWP',
    currencySymbol: 'P',
    currencyName: 'Botswana Pula',
    phoneCode: '+267',
    locale: 'en-BW',
    flag: '🇧🇼',
    isActive: true,
  },
  BR: {
    code: 'BR',
    name: 'Brazil',
    nativeName: 'Brasil',
    currencyCode: 'BRL',
    currencySymbol: 'R$',
    currencyName: 'Brazilian Real',
    phoneCode: '+55',
    locale: 'pt-BR',
    flag: '🇧🇷',
    isActive: true,
  },
  BN: {
    code: 'BN',
    name: 'Brunei',
    nativeName: 'Brunei',
    currencyCode: 'BND',
    currencySymbol: '$',
    currencyName: 'Brunei Dollar',
    phoneCode: '+673',
    locale: 'ms-BN',
    flag: '🇧🇳',
    isActive: true,
  },
  BG: {
    code: 'BG',
    name: 'Bulgaria',
    nativeName: 'България',
    currencyCode: 'BGN',
    currencySymbol: 'лв',
    currencyName: 'Bulgarian Lev',
    phoneCode: '+359',
    locale: 'bg-BG',
    flag: '🇧🇬',
    isActive: true,
  },
  BF: {
    code: 'BF',
    name: 'Burkina Faso',
    nativeName: 'Burkina Faso',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+226',
    locale: 'fr-BF',
    flag: '🇧🇫',
    isActive: true,
  },
  BI: {
    code: 'BI',
    name: 'Burundi',
    nativeName: 'Burundi',
    currencyCode: 'BIF',
    currencySymbol: 'FBu',
    currencyName: 'Burundian Franc',
    phoneCode: '+257',
    locale: 'rn-BI',
    flag: '🇧🇮',
    isActive: true,
  },
  CV: {
    code: 'CV',
    name: 'Cabo Verde',
    nativeName: 'Cabo Verde',
    currencyCode: 'CVE',
    currencySymbol: '$',
    currencyName: 'Cape Verdean Escudo',
    phoneCode: '+238',
    locale: 'pt-CV',
    flag: '🇨🇻',
    isActive: true,
  },
  KH: {
    code: 'KH',
    name: 'Cambodia',
    nativeName: 'កម្ពុជា',
    currencyCode: 'KHR',
    currencySymbol: '៛',
    currencyName: 'Cambodian Riel',
    phoneCode: '+855',
    locale: 'km-KH',
    flag: '🇰🇭',
    isActive: true,
  },
  CM: {
    code: 'CM',
    name: 'Cameroon',
    nativeName: 'Cameroun',
    currencyCode: 'XAF',
    currencySymbol: 'FCFA',
    currencyName: 'Central African CFA Franc',
    phoneCode: '+237',
    locale: 'fr-CM',
    flag: '🇨🇲',
    isActive: true,
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    nativeName: 'Canada',
    currencyCode: 'CAD',
    currencySymbol: '$',
    currencyName: 'Canadian Dollar',
    phoneCode: '+1',
    locale: 'en-CA',
    flag: '🇨🇦',
    isActive: true,
  },
  CF: {
    code: 'CF',
    name: 'Central African Republic',
    nativeName: 'République centrafricaine',
    currencyCode: 'XAF',
    currencySymbol: 'FCFA',
    currencyName: 'Central African CFA Franc',
    phoneCode: '+236',
    locale: 'fr-CF',
    flag: '🇨🇫',
    isActive: true,
  },
  TD: {
    code: 'TD',
    name: 'Chad',
    nativeName: 'Tchad',
    currencyCode: 'XAF',
    currencySymbol: 'FCFA',
    currencyName: 'Central African CFA Franc',
    phoneCode: '+235',
    locale: 'fr-TD',
    flag: '🇹🇩',
    isActive: true,
  },
  CL: {
    code: 'CL',
    name: 'Chile',
    nativeName: 'Chile',
    currencyCode: 'CLP',
    currencySymbol: '$',
    currencyName: 'Chilean Peso',
    phoneCode: '+56',
    locale: 'es-CL',
    flag: '🇨🇱',
    isActive: true,
  },
  CN: {
    code: 'CN',
    name: 'China',
    nativeName: '中国',
    currencyCode: 'CNY',
    currencySymbol: '¥',
    currencyName: 'Chinese Yuan',
    phoneCode: '+86',
    locale: 'zh-CN',
    flag: '🇨🇳',
    isActive: true,
  },
  CO: {
    code: 'CO',
    name: 'Colombia',
    nativeName: 'Colombia',
    currencyCode: 'COP',
    currencySymbol: '$',
    currencyName: 'Colombian Peso',
    phoneCode: '+57',
    locale: 'es-CO',
    flag: '🇨🇴',
    isActive: true,
  },
  KM: {
    code: 'KM',
    name: 'Comoros',
    nativeName: 'Komori',
    currencyCode: 'KMF',
    currencySymbol: 'CF',
    currencyName: 'Comorian Franc',
    phoneCode: '+269',
    locale: 'ar-KM',
    flag: '🇰🇲',
    isActive: true,
  },
  CG: {
    code: 'CG',
    name: 'Congo (Congo-Brazzaville)',
    nativeName: 'Congo',
    currencyCode: 'XAF',
    currencySymbol: 'FCFA',
    currencyName: 'Central African CFA Franc',
    phoneCode: '+242',
    locale: 'fr-CG',
    flag: '🇨🇬',
    isActive: true,
  },
  CD: {
    code: 'CD',
    name: 'Congo (Democratic Republic)',
    nativeName: 'République démocratique du Congo',
    currencyCode: 'CDF',
    currencySymbol: 'FC',
    currencyName: 'Congolese Franc',
    phoneCode: '+243',
    locale: 'fr-CD',
    flag: '🇨🇩',
    isActive: true,
  },
  CR: {
    code: 'CR',
    name: 'Costa Rica',
    nativeName: 'Costa Rica',
    currencyCode: 'CRC',
    currencySymbol: '₡',
    currencyName: 'Costa Rican Colón',
    phoneCode: '+506',
    locale: 'es-CR',
    flag: '🇨🇷',
    isActive: true,
  },
  HR: {
    code: 'HR',
    name: 'Croatia',
    nativeName: 'Hrvatska',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+385',
    locale: 'hr-HR',
    flag: '🇭🇷',
    isActive: true,
  },
  CU: {
    code: 'CU',
    name: 'Cuba',
    nativeName: 'Cuba',
    currencyCode: 'CUP',
    currencySymbol: '$',
    currencyName: 'Cuban Peso',
    phoneCode: '+53',
    locale: 'es-CU',
    flag: '🇨🇺',
    isActive: true,
  },
  CY: {
    code: 'CY',
    name: 'Cyprus',
    nativeName: 'Κύπρος',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+357',
    locale: 'el-CY',
    flag: '🇨🇾',
    isActive: true,
  },
  CZ: {
    code: 'CZ',
    name: 'Czechia',
    nativeName: 'Česko',
    currencyCode: 'CZK',
    currencySymbol: 'Kč',
    currencyName: 'Czech Koruna',
    phoneCode: '+420',
    locale: 'cs-CZ',
    flag: '🇨🇿',
    isActive: true,
  },
  DK: {
    code: 'DK',
    name: 'Denmark',
    nativeName: 'Danmark',
    currencyCode: 'DKK',
    currencySymbol: 'kr',
    currencyName: 'Danish Krone',
    phoneCode: '+45',
    locale: 'da-DK',
    flag: '🇩🇰',
    isActive: true,
  },
  DJ: {
    code: 'DJ',
    name: 'Djibouti',
    nativeName: 'Djibouti',
    currencyCode: 'DJF',
    currencySymbol: 'Fdj',
    currencyName: 'Djiboutian Franc',
    phoneCode: '+253',
    locale: 'fr-DJ',
    flag: '🇩🇯',
    isActive: true,
  },
  DM: {
    code: 'DM',
    name: 'Dominica',
    nativeName: 'Dominica',
    currencyCode: 'XCD',
    currencySymbol: '$',
    currencyName: 'East Caribbean Dollar',
    phoneCode: '+1767',
    locale: 'en-DM',
    flag: '🇩🇲',
    isActive: true,
  },
  DO: {
    code: 'DO',
    name: 'Dominican Republic',
    nativeName: 'República Dominicana',
    currencyCode: 'DOP',
    currencySymbol: '$',
    currencyName: 'Dominican Peso',
    phoneCode: '+1849',
    locale: 'es-DO',
    flag: '🇩🇴',
    isActive: true,
  },
  EC: {
    code: 'EC',
    name: 'Ecuador',
    nativeName: 'Ecuador',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+593',
    locale: 'es-EC',
    flag: '🇪🇨',
    isActive: true,
  },
  EG: {
    code: 'EG',
    name: 'Egypt',
    nativeName: 'مصر',
    currencyCode: 'EGP',
    currencySymbol: 'E£',
    currencyName: 'Egyptian Pound',
    phoneCode: '+20',
    locale: 'ar-EG',
    flag: '🇪🇬',
    isActive: true,
  },
  SV: {
    code: 'SV',
    name: 'El Salvador',
    nativeName: 'El Salvador',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+503',
    locale: 'es-SV',
    flag: '🇸🇻',
    isActive: true,
  },
  GQ: {
    code: 'GQ',
    name: 'Equatorial Guinea',
    nativeName: 'Guinea Ecuatorial',
    currencyCode: 'XAF',
    currencySymbol: 'FCFA',
    currencyName: 'Central African CFA Franc',
    phoneCode: '+240',
    locale: 'es-GQ',
    flag: '🇬🇶',
    isActive: true,
  },
  ER: {
    code: 'ER',
    name: 'Eritrea',
    nativeName: 'ኤርትራ',
    currencyCode: 'ERN',
    currencySymbol: 'Nfk',
    currencyName: 'Eritrean Nakfa',
    phoneCode: '+291',
    locale: 'ti-ER',
    flag: '🇪🇷',
    isActive: true,
  },
  EE: {
    code: 'EE',
    name: 'Estonia',
    nativeName: 'Eesti',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+372',
    locale: 'et-EE',
    flag: '🇪🇪',
    isActive: true,
  },
  SZ: {
    code: 'SZ',
    name: 'Eswatini (formerly Swaziland)',
    nativeName: 'Eswatini',
    currencyCode: 'SZL',
    currencySymbol: 'L',
    currencyName: 'Swazi Lilangeni',
    phoneCode: '+268',
    locale: 'en-SZ',
    flag: '🇸🇿',
    isActive: true,
  },
  ET: {
    code: 'ET',
    name: 'Ethiopia',
    nativeName: 'ኢትዮጵያ',
    currencyCode: 'ETB',
    currencySymbol: 'Br',
    currencyName: 'Ethiopian Birr',
    phoneCode: '+251',
    locale: 'am-ET',
    flag: '🇪🇹',
    isActive: true,
  },
  FJ: {
    code: 'FJ',
    name: 'Fiji',
    nativeName: 'Fiji',
    currencyCode: 'FJD',
    currencySymbol: '$',
    currencyName: 'Fijian Dollar',
    phoneCode: '+679',
    locale: 'en-FJ',
    flag: '🇫🇯',
    isActive: true,
  },
  FI: {
    code: 'FI',
    name: 'Finland',
    nativeName: 'Suomi',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+358',
    locale: 'fi-FI',
    flag: '🇫🇮',
    isActive: true,
  },
  FR: {
    code: 'FR',
    name: 'France',
    nativeName: 'France',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+33',
    locale: 'fr-FR',
    flag: '🇫🇷',
    isActive: true,
  },
  GA: {
    code: 'GA',
    name: 'Gabon',
    nativeName: 'Gabon',
    currencyCode: 'XAF',
    currencySymbol: 'FCFA',
    currencyName: 'Central African CFA Franc',
    phoneCode: '+241',
    locale: 'fr-GA',
    flag: '🇬🇦',
    isActive: true,
  },
  GM: {
    code: 'GM',
    name: 'Gambia',
    nativeName: 'Gambia',
    currencyCode: 'GMD',
    currencySymbol: 'D',
    currencyName: 'Gambian Dalasi',
    phoneCode: '+220',
    locale: 'en-GM',
    flag: '🇬🇲',
    isActive: true,
  },
  GE: {
    code: 'GE',
    name: 'Georgia',
    nativeName: 'საქართველო',
    currencyCode: 'GEL',
    currencySymbol: '₾',
    currencyName: 'Georgian Lari',
    phoneCode: '+995',
    locale: 'ka-GE',
    flag: '🇬🇪',
    isActive: true,
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    nativeName: 'Deutschland',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+49',
    locale: 'de-DE',
    flag: '🇩🇪',
    isActive: true,
  },
  GH: {
    code: 'GH',
    name: 'Ghana',
    nativeName: 'Ghana',
    currencyCode: 'GHS',
    currencySymbol: '₵',
    currencyName: 'Ghanaian Cedi',
    phoneCode: '+233',
    locale: 'en-GH',
    flag: '🇬🇭',
    isActive: true,
  },
  GR: {
    code: 'GR',
    name: 'Greece',
    nativeName: 'Ελλάδα',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+30',
    locale: 'el-GR',
    flag: '🇬🇷',
    isActive: true,
  },
  GD: {
    code: 'GD',
    name: 'Grenada',
    nativeName: 'Grenada',
    currencyCode: 'XCD',
    currencySymbol: '$',
    currencyName: 'East Caribbean Dollar',
    phoneCode: '+1473',
    locale: 'en-GD',
    flag: '🇬🇩',
    isActive: true,
  },
  GT: {
    code: 'GT',
    name: 'Guatemala',
    nativeName: 'Guatemala',
    currencyCode: 'GTQ',
    currencySymbol: 'Q',
    currencyName: 'Guatemalan Quetzal',
    phoneCode: '+502',
    locale: 'es-GT',
    flag: '🇬🇹',
    isActive: true,
  },
  GN: {
    code: 'GN',
    name: 'Guinea',
    nativeName: 'Guinée',
    currencyCode: 'GNF',
    currencySymbol: 'FG',
    currencyName: 'Guinean Franc',
    phoneCode: '+224',
    locale: 'fr-GN',
    flag: '🇬🇳',
    isActive: true,
  },
  GW: {
    code: 'GW',
    name: 'Guinea-Bissau',
    nativeName: 'Guiné-Bissau',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+245',
    locale: 'pt-GW',
    flag: '🇬🇼',
    isActive: true,
  },
  GY: {
    code: 'GY',
    name: 'Guyana',
    nativeName: 'Guyana',
    currencyCode: 'GYD',
    currencySymbol: '$',
    currencyName: 'Guyanese Dollar',
    phoneCode: '+592',
    locale: 'en-GY',
    flag: '🇬🇾',
    isActive: true,
  },
  HT: {
    code: 'HT',
    name: 'Haiti',
    nativeName: 'Haïti',
    currencyCode: 'HTG',
    currencySymbol: 'G',
    currencyName: 'Haitian Gourde',
    phoneCode: '+509',
    locale: 'fr-HT',
    flag: '🇭🇹',
    isActive: true,
  },
  HN: {
    code: 'HN',
    name: 'Honduras',
    nativeName: 'Honduras',
    currencyCode: 'HNL',
    currencySymbol: 'L',
    currencyName: 'Honduran Lempira',
    phoneCode: '+504',
    locale: 'es-HN',
    flag: '🇭🇳',
    isActive: true,
  },
  HU: {
    code: 'HU',
    name: 'Hungary',
    nativeName: 'Magyarország',
    currencyCode: 'HUF',
    currencySymbol: 'Ft',
    currencyName: 'Hungarian Forint',
    phoneCode: '+36',
    locale: 'hu-HU',
    flag: '🇭🇺',
    isActive: true,
  },
  IS: {
    code: 'IS',
    name: 'Iceland',
    nativeName: 'Ísland',
    currencyCode: 'ISK',
    currencySymbol: 'kr',
    currencyName: 'Icelandic Króna',
    phoneCode: '+354',
    locale: 'is-IS',
    flag: '🇮🇸',
    isActive: true,
  },
  IN: {
    code: 'IN',
    name: 'India',
    nativeName: 'भारत',
    currencyCode: 'INR',
    currencySymbol: '₹',
    currencyName: 'Indian Rupee',
    phoneCode: '+91',
    locale: 'en-IN',
    flag: '🇮🇳',
    isActive: true,
  },
  ID: {
    code: 'ID',
    name: 'Indonesia',
    nativeName: 'Indonesia',
    currencyCode: 'IDR',
    currencySymbol: 'Rp',
    currencyName: 'Indonesian Rupiah',
    phoneCode: '+62',
    locale: 'id-ID',
    flag: '🇮🇩',
    isActive: true,
  },
  IR: {
    code: 'IR',
    name: 'Iran',
    nativeName: 'ایران',
    currencyCode: 'IRR',
    currencySymbol: '﷼',
    currencyName: 'Iranian Rial',
    phoneCode: '+98',
    locale: 'fa-IR',
    flag: '🇮🇷',
    isActive: true,
  },
  IQ: {
    code: 'IQ',
    name: 'Iraq',
    nativeName: 'العراق',
    currencyCode: 'IQD',
    currencySymbol: 'ع.د',
    currencyName: 'Iraqi Dinar',
    phoneCode: '+964',
    locale: 'ar-IQ',
    flag: '🇮🇶',
    isActive: true,
  },
  IE: {
    code: 'IE',
    name: 'Ireland',
    nativeName: 'Éire',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+353',
    locale: 'en-IE',
    flag: '🇮🇪',
    isActive: true,
  },
  IL: {
    code: 'IL',
    name: 'Israel',
    nativeName: 'ישראל',
    currencyCode: 'ILS',
    currencySymbol: '₪',
    currencyName: 'Israeli New Shekel',
    phoneCode: '+972',
    locale: 'he-IL',
    flag: '🇮🇱',
    isActive: true,
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    nativeName: 'Italia',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+39',
    locale: 'it-IT',
    flag: '🇮🇹',
    isActive: true,
  },
  JM: {
    code: 'JM',
    name: 'Jamaica',
    nativeName: 'Jamaica',
    currencyCode: 'JMD',
    currencySymbol: '$',
    currencyName: 'Jamaican Dollar',
    phoneCode: '+1876',
    locale: 'en-JM',
    flag: '🇯🇲',
    isActive: true,
  },
  JP: {
    code: 'JP',
    name: 'Japan',
    nativeName: '日本',
    currencyCode: 'JPY',
    currencySymbol: '¥',
    currencyName: 'Japanese Yen',
    phoneCode: '+81',
    locale: 'ja-JP',
    flag: '🇯🇵',
    isActive: true,
  },
  JO: {
    code: 'JO',
    name: 'Jordan',
    nativeName: 'الأردن',
    currencyCode: 'JOD',
    currencySymbol: 'د.ا',
    currencyName: 'Jordanian Dinar',
    phoneCode: '+962',
    locale: 'ar-JO',
    flag: '🇯🇴',
    isActive: true,
  },
  KZ: {
    code: 'KZ',
    name: 'Kazakhstan',
    nativeName: 'Қазақстан',
    currencyCode: 'KZT',
    currencySymbol: '₸',
    currencyName: 'Kazakhstani Tenge',
    phoneCode: '+7',
    locale: 'kk-KZ',
    flag: '🇰🇿',
    isActive: true,
  },
  KE: {
    code: 'KE',
    name: 'Kenya',
    nativeName: 'Kenya',
    currencyCode: 'KES',
    currencySymbol: 'KSh',
    currencyName: 'Kenyan Shilling',
    phoneCode: '+254',
    locale: 'en-KE',
    flag: '🇰🇪',
    isActive: true,
  },
  KI: {
    code: 'KI',
    name: 'Kiribati',
    nativeName: 'Kiribati',
    currencyCode: 'AUD',
    currencySymbol: '$',
    currencyName: 'Australian Dollar',
    phoneCode: '+686',
    locale: 'en-KI',
    flag: '🇰🇮',
    isActive: true,
  },
  KP: {
    code: 'KP',
    name: 'North Korea',
    nativeName: '조선',
    currencyCode: 'KPW',
    currencySymbol: '₩',
    currencyName: 'North Korean Won',
    phoneCode: '+850',
    locale: 'ko-KP',
    flag: '🇰🇵',
    isActive: true,
  },
  KR: {
    code: 'KR',
    name: 'South Korea',
    nativeName: '대한민국',
    currencyCode: 'KRW',
    currencySymbol: '₩',
    currencyName: 'South Korean Won',
    phoneCode: '+82',
    locale: 'ko-KR',
    flag: '🇰🇷',
    isActive: true,
  },
  KW: {
    code: 'KW',
    name: 'Kuwait',
    nativeName: 'الكويت',
    currencyCode: 'KWD',
    currencySymbol: 'د.ك',
    currencyName: 'Kuwaiti Dinar',
    phoneCode: '+965',
    locale: 'ar-KW',
    flag: '🇰🇼',
    isActive: true,
  },
  KG: {
    code: 'KG',
    name: 'Kyrgyzstan',
    nativeName: 'Кыргызстан',
    currencyCode: 'KGS',
    currencySymbol: 'с',
    currencyName: 'Kyrgyzstani Som',
    phoneCode: '+996',
    locale: 'ky-KG',
    flag: '🇰🇬',
    isActive: true,
  },
  LA: {
    code: 'LA',
    name: 'Laos',
    nativeName: 'ລາວ',
    currencyCode: 'LAK',
    currencySymbol: '₭',
    currencyName: 'Lao Kip',
    phoneCode: '+856',
    locale: 'lo-LA',
    flag: '🇱🇦',
    isActive: true,
  },
  LV: {
    code: 'LV',
    name: 'Latvia',
    nativeName: 'Latvija',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+371',
    locale: 'lv-LV',
    flag: '🇱🇻',
    isActive: true,
  },
  LB: {
    code: 'LB',
    name: 'Lebanon',
    nativeName: 'لبنان',
    currencyCode: 'LBP',
    currencySymbol: 'ل.ل',
    currencyName: 'Lebanese Pound',
    phoneCode: '+961',
    locale: 'ar-LB',
    flag: '🇱🇧',
    isActive: true,
  },
  LS: {
    code: 'LS',
    name: 'Lesotho',
    nativeName: 'Lesotho',
    currencyCode: 'LSL',
    currencySymbol: 'L',
    currencyName: 'Lesotho Loti',
    phoneCode: '+266',
    locale: 'st-LS',
    flag: '🇱🇸',
    isActive: true,
  },
  LR: {
    code: 'LR',
    name: 'Liberia',
    nativeName: 'Liberia',
    currencyCode: 'LRD',
    currencySymbol: '$',
    currencyName: 'Liberian Dollar',
    phoneCode: '+231',
    locale: 'en-LR',
    flag: '🇱🇷',
    isActive: true,
  },
  LY: {
    code: 'LY',
    name: 'Libya',
    nativeName: 'ليبيا',
    currencyCode: 'LYD',
    currencySymbol: 'ل.د',
    currencyName: 'Libyan Dinar',
    phoneCode: '+218',
    locale: 'ar-LY',
    flag: '🇱🇾',
    isActive: true,
  },
  LI: {
    code: 'LI',
    name: 'Liechtenstein',
    nativeName: 'Liechtenstein',
    currencyCode: 'CHF',
    currencySymbol: 'Fr',
    currencyName: 'Swiss Franc',
    phoneCode: '+423',
    locale: 'de-LI',
    flag: '🇱🇮',
    isActive: true,
  },
  LT: {
    code: 'LT',
    name: 'Lithuania',
    nativeName: 'Lietuva',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+370',
    locale: 'lt-LT',
    flag: '🇱🇹',
    isActive: true,
  },
  LU: {
    code: 'LU',
    name: 'Luxembourg',
    nativeName: 'Luxembourg',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+352',
    locale: 'fr-LU',
    flag: '🇱🇺',
    isActive: true,
  },
  MG: {
    code: 'MG',
    name: 'Madagascar',
    nativeName: 'Madagasikara',
    currencyCode: 'MGA',
    currencySymbol: 'Ar',
    currencyName: 'Malagasy Ariary',
    phoneCode: '+261',
    locale: 'mg-MG',
    flag: '🇲🇬',
    isActive: true,
  },
  MW: {
    code: 'MW',
    name: 'Malawi',
    nativeName: 'Malawi',
    currencyCode: 'MWK',
    currencySymbol: 'MK',
    currencyName: 'Malawian Kwacha',
    phoneCode: '+265',
    locale: 'en-MW',
    flag: '🇲🇼',
    isActive: true,
  },
  MY: {
    code: 'MY',
    name: 'Malaysia',
    nativeName: 'Malaysia',
    currencyCode: 'MYR',
    currencySymbol: 'RM',
    currencyName: 'Malaysian Ringgit',
    phoneCode: '+60',
    locale: 'ms-MY',
    flag: '🇲🇾',
    isActive: true,
  },
  MV: {
    code: 'MV',
    name: 'Maldives',
    nativeName: 'ދިވެހިރާއްޖެ',
    currencyCode: 'MVR',
    currencySymbol: 'ރ.',
    currencyName: 'Maldivian Rufiyaa',
    phoneCode: '+960',
    locale: 'dv-MV',
    flag: '🇲🇻',
    isActive: true,
  },
  ML: {
    code: 'ML',
    name: 'Mali',
    nativeName: 'Mali',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+223',
    locale: 'fr-ML',
    flag: '🇲🇱',
    isActive: true,
  },
  MT: {
    code: 'MT',
    name: 'Malta',
    nativeName: 'Malta',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+356',
    locale: 'mt-MT',
    flag: '🇲🇹',
    isActive: true,
  },
  MH: {
    code: 'MH',
    name: 'Marshall Islands',
    nativeName: 'Marshall Islands',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+692',
    locale: 'en-MH',
    flag: '🇲🇭',
    isActive: true,
  },
  MR: {
    code: 'MR',
    name: 'Mauritania',
    nativeName: 'موريتانيا',
    currencyCode: 'MRU',
    currencySymbol: 'UM',
    currencyName: 'Mauritanian Ouguiya',
    phoneCode: '+222',
    locale: 'ar-MR',
    flag: '🇲🇷',
    isActive: true,
  },
  MU: {
    code: 'MU',
    name: 'Mauritius',
    nativeName: 'Maurice',
    currencyCode: 'MUR',
    currencySymbol: '₨',
    currencyName: 'Mauritian Rupee',
    phoneCode: '+230',
    locale: 'en-MU',
    flag: '🇲🇺',
    isActive: true,
  },
  MX: {
    code: 'MX',
    name: 'Mexico',
    nativeName: 'México',
    currencyCode: 'MXN',
    currencySymbol: '$',
    currencyName: 'Mexican Peso',
    phoneCode: '+52',
    locale: 'es-MX',
    flag: '🇲🇽',
    isActive: true,
  },
  FM: {
    code: 'FM',
    name: 'Micronesia',
    nativeName: 'Micronesia',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+691',
    locale: 'en-FM',
    flag: '🇫🇲',
    isActive: true,
  },
  MD: {
    code: 'MD',
    name: 'Moldova',
    nativeName: 'Moldova',
    currencyCode: 'MDL',
    currencySymbol: 'L',
    currencyName: 'Moldovan Leu',
    phoneCode: '+373',
    locale: 'ro-MD',
    flag: '🇲🇩',
    isActive: true,
  },
  MC: {
    code: 'MC',
    name: 'Monaco',
    nativeName: 'Monaco',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+377',
    locale: 'fr-MC',
    flag: '🇲🇨',
    isActive: true,
  },
  MN: {
    code: 'MN',
    name: 'Mongolia',
    nativeName: 'Монгол Улс',
    currencyCode: 'MNT',
    currencySymbol: '₮',
    currencyName: 'Mongolian Tögrög',
    phoneCode: '+976',
    locale: 'mn-MN',
    flag: '🇲🇳',
    isActive: true,
  },
  ME: {
    code: 'ME',
    name: 'Montenegro',
    nativeName: 'Црна Гора',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+382',
    locale: 'sr-ME',
    flag: '🇲🇪',
    isActive: true,
  },
  MA: {
    code: 'MA',
    name: 'Morocco',
    nativeName: 'المغرب',
    currencyCode: 'MAD',
    currencySymbol: 'د.م.',
    currencyName: 'Moroccan Dirham',
    phoneCode: '+212',
    locale: 'ar-MA',
    flag: '🇲🇦',
    isActive: true,
  },
  MZ: {
    code: 'MZ',
    name: 'Mozambique',
    nativeName: 'Moçambique',
    currencyCode: 'MZN',
    currencySymbol: 'MT',
    currencyName: 'Mozambican Metical',
    phoneCode: '+258',
    locale: 'pt-MZ',
    flag: '🇲🇿',
    isActive: true,
  },
  MM: {
    code: 'MM',
    name: 'Myanmar (Burma)',
    nativeName: 'မြန်မာ',
    currencyCode: 'MMK',
    currencySymbol: 'Ks',
    currencyName: 'Myanmar Kyat',
    phoneCode: '+95',
    locale: 'my-MM',
    flag: '🇲🇲',
    isActive: true,
  },
  NA: {
    code: 'NA',
    name: 'Namibia',
    nativeName: 'Namibia',
    currencyCode: 'NAD',
    currencySymbol: '$',
    currencyName: 'Namibian Dollar',
    phoneCode: '+264',
    locale: 'en-NA',
    flag: '🇳🇦',
    isActive: true,
  },
  NR: {
    code: 'NR',
    name: 'Nauru',
    nativeName: 'Nauru',
    currencyCode: 'AUD',
    currencySymbol: '$',
    currencyName: 'Australian Dollar',
    phoneCode: '+674',
    locale: 'en-NR',
    flag: '🇳🇷',
    isActive: true,
  },
  NP: {
    code: 'NP',
    name: 'Nepal',
    nativeName: 'नेपाल',
    currencyCode: 'NPR',
    currencySymbol: '₨',
    currencyName: 'Nepalese Rupee',
    phoneCode: '+977',
    locale: 'ne-NP',
    flag: '🇳🇵',
    isActive: true,
  },
  NL: {
    code: 'NL',
    name: 'Netherlands',
    nativeName: 'Nederland',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+31',
    locale: 'nl-NL',
    flag: '🇳🇱',
    isActive: true,
  },
  NZ: {
    code: 'NZ',
    name: 'New Zealand',
    nativeName: 'New Zealand',
    currencyCode: 'NZD',
    currencySymbol: '$',
    currencyName: 'New Zealand Dollar',
    phoneCode: '+64',
    locale: 'en-NZ',
    flag: '🇳🇿',
    isActive: true,
  },
  NI: {
    code: 'NI',
    name: 'Nicaragua',
    nativeName: 'Nicaragua',
    currencyCode: 'NIO',
    currencySymbol: 'C$',
    currencyName: 'Nicaraguan Córdoba',
    phoneCode: '+505',
    locale: 'es-NI',
    flag: '🇳🇮',
    isActive: true,
  },
  NE: {
    code: 'NE',
    name: 'Niger',
    nativeName: 'Niger',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+227',
    locale: 'fr-NE',
    flag: '🇳🇪',
    isActive: true,
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    nativeName: 'Nigeria',
    currencyCode: 'NGN',
    currencySymbol: '₦',
    currencyName: 'Nigerian Naira',
    phoneCode: '+234',
    locale: 'en-NG',
    flag: '🇳🇬',
    isActive: true,
  },
  MK: {
    code: 'MK',
    name: 'North Macedonia',
    nativeName: 'Северна Македонија',
    currencyCode: 'MKD',
    currencySymbol: 'ден',
    currencyName: 'Macedonian Denar',
    phoneCode: '+389',
    locale: 'mk-MK',
    flag: '🇲🇰',
    isActive: true,
  },
  NO: {
    code: 'NO',
    name: 'Norway',
    nativeName: 'Norge',
    currencyCode: 'NOK',
    currencySymbol: 'kr',
    currencyName: 'Norwegian Krone',
    phoneCode: '+47',
    locale: 'nb-NO',
    flag: '🇳🇴',
    isActive: true,
  },
  OM: {
    code: 'OM',
    name: 'Oman',
    nativeName: 'عُمان',
    currencyCode: 'OMR',
    currencySymbol: 'ر.ع.',
    currencyName: 'Omani Rial',
    phoneCode: '+968',
    locale: 'ar-OM',
    flag: '🇴🇲',
    isActive: true,
  },
  PK: {
    code: 'PK',
    name: 'Pakistan',
    nativeName: 'پاکستان',
    currencyCode: 'PKR',
    currencySymbol: '₨',
    currencyName: 'Pakistani Rupee',
    phoneCode: '+92',
    locale: 'ur-PK',
    flag: '🇵🇰',
    isActive: true,
  },
  PW: {
    code: 'PW',
    name: 'Palau',
    nativeName: 'Palau',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+680',
    locale: 'en-PW',
    flag: '🇵🇼',
    isActive: true,
  },
  PS: {
    code: 'PS',
    name: 'Palestine',
    nativeName: 'فلسطين',
    currencyCode: 'ILS',
    currencySymbol: '₪',
    currencyName: 'Israeli New Shekel',
    phoneCode: '+970',
    locale: 'ar-PS',
    flag: '🇵🇸',
    isActive: true,
  },
  PA: {
    code: 'PA',
    name: 'Panama',
    nativeName: 'Panamá',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+507',
    locale: 'es-PA',
    flag: '🇵🇦',
    isActive: true,
  },
  PG: {
    code: 'PG',
    name: 'Papua New Guinea',
    nativeName: 'Papua New Guinea',
    currencyCode: 'PGK',
    currencySymbol: 'K',
    currencyName: 'Papua New Guinean Kina',
    phoneCode: '+675',
    locale: 'en-PG',
    flag: '🇵🇬',
    isActive: true,
  },
  PY: {
    code: 'PY',
    name: 'Paraguay',
    nativeName: 'Paraguay',
    currencyCode: 'PYG',
    currencySymbol: '₲',
    currencyName: 'Paraguayan Guaraní',
    phoneCode: '+595',
    locale: 'es-PY',
    flag: '🇵🇾',
    isActive: true,
  },
  PE: {
    code: 'PE',
    name: 'Peru',
    nativeName: 'Perú',
    currencyCode: 'PEN',
    currencySymbol: 'S/',
    currencyName: 'Peruvian Sol',
    phoneCode: '+51',
    locale: 'es-PE',
    flag: '🇵🇪',
    isActive: true,
  },
  PH: {
    code: 'PH',
    name: 'Philippines',
    nativeName: 'Pilipinas',
    currencyCode: 'PHP',
    currencySymbol: '₱',
    currencyName: 'Philippine Peso',
    phoneCode: '+63',
    locale: 'en-PH',
    flag: '🇵🇭',
    isActive: true,
  },
  PL: {
    code: 'PL',
    name: 'Poland',
    nativeName: 'Polska',
    currencyCode: 'PLN',
    currencySymbol: 'zł',
    currencyName: 'Polish Złoty',
    phoneCode: '+48',
    locale: 'pl-PL',
    flag: '🇵🇱',
    isActive: true,
  },
  PT: {
    code: 'PT',
    name: 'Portugal',
    nativeName: 'Portugal',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+351',
    locale: 'pt-PT',
    flag: '🇵🇹',
    isActive: true,
  },
  QA: {
    code: 'QA',
    name: 'Qatar',
    nativeName: 'قطر',
    currencyCode: 'QAR',
    currencySymbol: 'ر.ق',
    currencyName: 'Qatari Riyal',
    phoneCode: '+974',
    locale: 'ar-QA',
    flag: '🇶🇦',
    isActive: true,
  },
  RO: {
    code: 'RO',
    name: 'Romania',
    nativeName: 'România',
    currencyCode: 'RON',
    currencySymbol: 'lei',
    currencyName: 'Romanian Leu',
    phoneCode: '+40',
    locale: 'ro-RO',
    flag: '🇷🇴',
    isActive: true,
  },
  RU: {
    code: 'RU',
    name: 'Russia',
    nativeName: 'Россия',
    currencyCode: 'RUB',
    currencySymbol: '₽',
    currencyName: 'Russian Ruble',
    phoneCode: '+7',
    locale: 'ru-RU',
    flag: '🇷🇺',
    isActive: true,
  },
  RW: {
    code: 'RW',
    name: 'Rwanda',
    nativeName: 'Rwanda',
    currencyCode: 'RWF',
    currencySymbol: 'FRw',
    currencyName: 'Rwandan Franc',
    phoneCode: '+250',
    locale: 'rw-RW',
    flag: '🇷🇼',
    isActive: true,
  },
  KN: {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    nativeName: 'Saint Kitts and Nevis',
    currencyCode: 'XCD',
    currencySymbol: '$',
    currencyName: 'East Caribbean Dollar',
    phoneCode: '+1869',
    locale: 'en-KN',
    flag: '🇰🇳',
    isActive: true,
  },
  LC: {
    code: 'LC',
    name: 'Saint Lucia',
    nativeName: 'Saint Lucia',
    currencyCode: 'XCD',
    currencySymbol: '$',
    currencyName: 'East Caribbean Dollar',
    phoneCode: '+1758',
    locale: 'en-LC',
    flag: '🇱🇨',
    isActive: true,
  },
  VC: {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    nativeName: 'Saint Vincent and the Grenadines',
    currencyCode: 'XCD',
    currencySymbol: '$',
    currencyName: 'East Caribbean Dollar',
    phoneCode: '+1784',
    locale: 'en-VC',
    flag: '🇻🇨',
    isActive: true,
  },
  WS: {
    code: 'WS',
    name: 'Samoa',
    nativeName: 'Samoa',
    currencyCode: 'WST',
    currencySymbol: 'T',
    currencyName: 'Samoan Tālā',
    phoneCode: '+685',
    locale: 'en-WS',
    flag: '🇼🇸',
    isActive: true,
  },
  SM: {
    code: 'SM',
    name: 'San Marino',
    nativeName: 'San Marino',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+378',
    locale: 'it-SM',
    flag: '🇸🇲',
    isActive: true,
  },
  ST: {
    code: 'ST',
    name: 'Sao Tome and Principe',
    nativeName: 'São Tomé e Príncipe',
    currencyCode: 'STN',
    currencySymbol: 'Db',
    currencyName: 'São Tomé and Príncipe Dobra',
    phoneCode: '+239',
    locale: 'pt-ST',
    flag: '🇸🇹',
    isActive: true,
  },
  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    nativeName: 'المملكة العربية السعودية',
    currencyCode: 'SAR',
    currencySymbol: 'ر.س',
    currencyName: 'Saudi Riyal',
    phoneCode: '+966',
    locale: 'ar-SA',
    flag: '🇸🇦',
    isActive: true,
  },
  SN: {
    code: 'SN',
    name: 'Senegal',
    nativeName: 'Sénégal',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+221',
    locale: 'fr-SN',
    flag: '🇸🇳',
    isActive: true,
  },
  RS: {
    code: 'RS',
    name: 'Serbia',
    nativeName: 'Србија',
    currencyCode: 'RSD',
    currencySymbol: 'дин',
    currencyName: 'Serbian Dinar',
    phoneCode: '+381',
    locale: 'sr-RS',
    flag: '🇷🇸',
    isActive: true,
  },
  SC: {
    code: 'SC',
    name: 'Seychelles',
    nativeName: 'Seychelles',
    currencyCode: 'SCR',
    currencySymbol: '₨',
    currencyName: 'Seychellois Rupee',
    phoneCode: '+248',
    locale: 'en-SC',
    flag: '🇸🇨',
    isActive: true,
  },
  SL: {
    code: 'SL',
    name: 'Sierra Leone',
    nativeName: 'Sierra Leone',
    currencyCode: 'SLE',
    currencySymbol: 'Le',
    currencyName: 'Sierra Leonean Leone',
    phoneCode: '+232',
    locale: 'en-SL',
    flag: '🇸🇱',
    isActive: true,
  },
  SG: {
    code: 'SG',
    name: 'Singapore',
    nativeName: 'Singapore',
    currencyCode: 'SGD',
    currencySymbol: '$',
    currencyName: 'Singapore Dollar',
    phoneCode: '+65',
    locale: 'en-SG',
    flag: '🇸🇬',
    isActive: true,
  },
  SK: {
    code: 'SK',
    name: 'Slovakia',
    nativeName: 'Slovensko',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+421',
    locale: 'sk-SK',
    flag: '🇸🇰',
    isActive: true,
  },
  SI: {
    code: 'SI',
    name: 'Slovenia',
    nativeName: 'Slovenija',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+386',
    locale: 'sl-SI',
    flag: '🇸🇮',
    isActive: true,
  },
  SB: {
    code: 'SB',
    name: 'Solomon Islands',
    nativeName: 'Solomon Islands',
    currencyCode: 'SBD',
    currencySymbol: '$',
    currencyName: 'Solomon Islands Dollar',
    phoneCode: '+677',
    locale: 'en-SB',
    flag: '🇸🇧',
    isActive: true,
  },
  SO: {
    code: 'SO',
    name: 'Somalia',
    nativeName: 'Soomaaliya',
    currencyCode: 'SOS',
    currencySymbol: 'S',
    currencyName: 'Somali Shilling',
    phoneCode: '+252',
    locale: 'so-SO',
    flag: '🇸🇴',
    isActive: true,
  },
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    nativeName: 'South Africa',
    currencyCode: 'ZAR',
    currencySymbol: 'R',
    currencyName: 'South African Rand',
    phoneCode: '+27',
    locale: 'en-ZA',
    flag: '🇿🇦',
    isActive: true,
  },
  SS: {
    code: 'SS',
    name: 'South Sudan',
    nativeName: 'South Sudan',
    currencyCode: 'SSP',
    currencySymbol: '£',
    currencyName: 'South Sudanese Pound',
    phoneCode: '+211',
    locale: 'en-SS',
    flag: '🇸🇸',
    isActive: true,
  },
  ES: {
    code: 'ES',
    name: 'Spain',
    nativeName: 'España',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+34',
    locale: 'es-ES',
    flag: '🇪🇸',
    isActive: true,
  },
  LK: {
    code: 'LK',
    name: 'Sri Lanka',
    nativeName: 'ශ්‍රී ලංකාව',
    currencyCode: 'LKR',
    currencySymbol: 'Rs',
    currencyName: 'Sri Lankan Rupee',
    phoneCode: '+94',
    locale: 'si-LK',
    flag: '🇱🇰',
    isActive: true,
  },
  SD: {
    code: 'SD',
    name: 'Sudan',
    nativeName: 'السودان',
    currencyCode: 'SDG',
    currencySymbol: 'ج.س.',
    currencyName: 'Sudanese Pound',
    phoneCode: '+249',
    locale: 'ar-SD',
    flag: '🇸🇩',
    isActive: true,
  },
  SR: {
    code: 'SR',
    name: 'Suriname',
    nativeName: 'Suriname',
    currencyCode: 'SRD',
    currencySymbol: '$',
    currencyName: 'Surinamese Dollar',
    phoneCode: '+597',
    locale: 'nl-SR',
    flag: '🇸🇷',
    isActive: true,
  },
  SE: {
    code: 'SE',
    name: 'Sweden',
    nativeName: 'Sverige',
    currencyCode: 'SEK',
    currencySymbol: 'kr',
    currencyName: 'Swedish Krona',
    phoneCode: '+46',
    locale: 'sv-SE',
    flag: '🇸🇪',
    isActive: true,
  },
  CH: {
    code: 'CH',
    name: 'Switzerland',
    nativeName: 'Schweiz',
    currencyCode: 'CHF',
    currencySymbol: 'Fr',
    currencyName: 'Swiss Franc',
    phoneCode: '+41',
    locale: 'de-CH',
    flag: '🇨🇭',
    isActive: true,
  },
  SY: {
    code: 'SY',
    name: 'Syria',
    nativeName: 'سوريا',
    currencyCode: 'SYP',
    currencySymbol: 'ل.س',
    currencyName: 'Syrian Pound',
    phoneCode: '+963',
    locale: 'ar-SY',
    flag: '🇸🇾',
    isActive: true,
  },
  TJ: {
    code: 'TJ',
    name: 'Tajikistan',
    nativeName: 'Тоҷикистон',
    currencyCode: 'TJS',
    currencySymbol: 'ЅМ',
    currencyName: 'Tajikistani Somoni',
    phoneCode: '+992',
    locale: 'tg-TJ',
    flag: '🇹🇯',
    isActive: true,
  },
  TZ: {
    code: 'TZ',
    name: 'Tanzania',
    nativeName: 'Tanzania',
    currencyCode: 'TZS',
    currencySymbol: 'TSh',
    currencyName: 'Tanzanian Shilling',
    phoneCode: '+255',
    locale: 'sw-TZ',
    flag: '🇹🇿',
    isActive: true,
  },
  TH: {
    code: 'TH',
    name: 'Thailand',
    nativeName: 'ประเทศไทย',
    currencyCode: 'THB',
    currencySymbol: '฿',
    currencyName: 'Thai Baht',
    phoneCode: '+66',
    locale: 'th-TH',
    flag: '🇹🇭',
    isActive: true,
  },
  TL: {
    code: 'TL',
    name: 'Timor-Leste',
    nativeName: 'Timor-Leste',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+670',
    locale: 'pt-TL',
    flag: '🇹🇱',
    isActive: true,
  },
  TG: {
    code: 'TG',
    name: 'Togo',
    nativeName: 'Togo',
    currencyCode: 'XOF',
    currencySymbol: 'CFA',
    currencyName: 'West African CFA Franc',
    phoneCode: '+228',
    locale: 'fr-TG',
    flag: '🇹🇬',
    isActive: true,
  },
  TO: {
    code: 'TO',
    name: 'Tonga',
    nativeName: 'Tonga',
    currencyCode: 'TOP',
    currencySymbol: 'T$',
    currencyName: 'Tongan Paʻanga',
    phoneCode: '+676',
    locale: 'to-TO',
    flag: '🇹🇴',
    isActive: true,
  },
  TT: {
    code: 'TT',
    name: 'Trinidad and Tobago',
    nativeName: 'Trinidad and Tobago',
    currencyCode: 'TTD',
    currencySymbol: '$',
    currencyName: 'Trinidad and Tobago Dollar',
    phoneCode: '+1868',
    locale: 'en-TT',
    flag: '🇹🇹',
    isActive: true,
  },
  TN: {
    code: 'TN',
    name: 'Tunisia',
    nativeName: 'تونس',
    currencyCode: 'TND',
    currencySymbol: 'د.ت',
    currencyName: 'Tunisian Dinar',
    phoneCode: '+216',
    locale: 'ar-TN',
    flag: '🇹🇳',
    isActive: true,
  },
  TR: {
    code: 'TR',
    name: 'Turkey',
    nativeName: 'Türkiye',
    currencyCode: 'TRY',
    currencySymbol: '₺',
    currencyName: 'Turkish Lira',
    phoneCode: '+90',
    locale: 'tr-TR',
    flag: '🇹🇷',
    isActive: true,
  },
  TM: {
    code: 'TM',
    name: 'Turkmenistan',
    nativeName: 'Türkmenistan',
    currencyCode: 'TMT',
    currencySymbol: 'm',
    currencyName: 'Turkmenistan Manat',
    phoneCode: '+993',
    locale: 'tk-TM',
    flag: '🇹🇲',
    isActive: true,
  },
  TV: {
    code: 'TV',
    name: 'Tuvalu',
    nativeName: 'Tuvalu',
    currencyCode: 'AUD',
    currencySymbol: '$',
    currencyName: 'Australian Dollar',
    phoneCode: '+688',
    locale: 'en-TV',
    flag: '🇹🇻',
    isActive: true,
  },
  UG: {
    code: 'UG',
    name: 'Uganda',
    nativeName: 'Uganda',
    currencyCode: 'UGX',
    currencySymbol: 'USh',
    currencyName: 'Ugandan Shilling',
    phoneCode: '+256',
    locale: 'en-UG',
    flag: '🇺🇬',
    isActive: true,
  },
  UA: {
    code: 'UA',
    name: 'Ukraine',
    nativeName: 'Україна',
    currencyCode: 'UAH',
    currencySymbol: '₴',
    currencyName: 'Ukrainian Hryvnia',
    phoneCode: '+380',
    locale: 'uk-UA',
    flag: '🇺🇦',
    isActive: true,
  },
  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    nativeName: 'الإمارات العربية المتحدة',
    currencyCode: 'AED',
    currencySymbol: 'د.إ',
    currencyName: 'UAE Dirham',
    phoneCode: '+971',
    locale: 'ar-AE',
    flag: '🇦🇪',
    isActive: true,
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    nativeName: 'United Kingdom',
    currencyCode: 'GBP',
    currencySymbol: '£',
    currencyName: 'British Pound',
    phoneCode: '+44',
    locale: 'en-GB',
    flag: '🇬🇧',
    isActive: true,
  },
  US: {
    code: 'US',
    name: 'United States',
    nativeName: 'United States',
    currencyCode: 'USD',
    currencySymbol: '$',
    currencyName: 'US Dollar',
    phoneCode: '+1',
    locale: 'en-US',
    flag: '🇺🇸',
    isActive: true,
  },
  UY: {
    code: 'UY',
    name: 'Uruguay',
    nativeName: 'Uruguay',
    currencyCode: 'UYU',
    currencySymbol: '$',
    currencyName: 'Uruguayan Peso',
    phoneCode: '+598',
    locale: 'es-UY',
    flag: '🇺🇾',
    isActive: true,
  },
  UZ: {
    code: 'UZ',
    name: 'Uzbekistan',
    nativeName: 'Oʻzbekiston',
    currencyCode: 'UZS',
    currencySymbol: 'soʻm',
    currencyName: 'Uzbekistani Soʻm',
    phoneCode: '+998',
    locale: 'uz-UZ',
    flag: '🇺🇿',
    isActive: true,
  },
  VU: {
    code: 'VU',
    name: 'Vanuatu',
    nativeName: 'Vanuatu',
    currencyCode: 'VUV',
    currencySymbol: 'VT',
    currencyName: 'Vanuatu Vatu',
    phoneCode: '+678',
    locale: 'bi-VU',
    flag: '🇻🇺',
    isActive: true,
  },
  VA: {
    code: 'VA',
    name: 'Holy See (Vatican City)',
    nativeName: 'Santa Sede',
    currencyCode: 'EUR',
    currencySymbol: '€',
    currencyName: 'Euro',
    phoneCode: '+379',
    locale: 'it-VA',
    flag: '🇻🇦',
    isActive: true,
  },
  VE: {
    code: 'VE',
    name: 'Venezuela',
    nativeName: 'Venezuela',
    currencyCode: 'VES',
    currencySymbol: 'Bs.',
    currencyName: 'Venezuelan Bolívar',
    phoneCode: '+58',
    locale: 'es-VE',
    flag: '🇻🇪',
    isActive: true,
  },
  VN: {
    code: 'VN',
    name: 'Vietnam',
    nativeName: 'Việt Nam',
    currencyCode: 'VND',
    currencySymbol: '₫',
    currencyName: 'Vietnamese Đồng',
    phoneCode: '+84',
    locale: 'vi-VN',
    flag: '🇻🇳',
    isActive: true,
  },
  YE: {
    code: 'YE',
    name: 'Yemen',
    nativeName: 'اليمن',
    currencyCode: 'YER',
    currencySymbol: 'ر.ي',
    currencyName: 'Yemeni Rial',
    phoneCode: '+967',
    locale: 'ar-YE',
    flag: '🇾🇪',
    isActive: true,
  },
  ZM: {
    code: 'ZM',
    name: 'Zambia',
    nativeName: 'Zambia',
    currencyCode: 'ZMW',
    currencySymbol: 'ZK',
    currencyName: 'Zambian Kwacha',
    phoneCode: '+260',
    locale: 'en-ZM',
    flag: '🇿🇲',
    isActive: true,
  },
  ZW: {
    code: 'ZW',
    name: 'Zimbabwe',
    nativeName: 'Zimbabwe',
    currencyCode: 'ZWL',
    currencySymbol: '$',
    currencyName: 'Zimbabwean Dollar',
    phoneCode: '+263',
    locale: 'en-ZW',
    flag: '🇿🇼',
    isActive: true,
  },
};

/**
 * Validate that we have exactly 195 countries
 * This ensures all UN members + Holy See + Palestine are included
 */
export const COUNTRY_COUNT = Object.keys(COUNTRIES).length;

// Validation constant that can be used in tests
export const VALIDATION = {
  expectedCount: 195,
  actualCount: COUNTRY_COUNT,
  isValid: COUNTRY_COUNT === 195,
};

/**
 * Get country configuration by ISO alpha-2 code
 */
export const getCountryByCode = (code: string): CountryConfig | undefined => {
  return COUNTRIES[code.toUpperCase()];
};

/**
 * Get currency code for a country
 */
export const getCurrencyByCountry = (
  countryCode: string,
): string | undefined => {
  const country = getCountryByCode(countryCode);
  return country?.currencyCode;
};

/**
 * Get currency symbol for a country
 */
export const getCountryCurrencySymbol = (
  countryCode: string,
): string | undefined => {
  const country = getCountryByCode(countryCode);
  return country?.currencySymbol;
};

/**
 * Check if a country code is valid (exists in our configuration)
 */
export const isValidCountryCode = (code: string): boolean => {
  return !!COUNTRIES[code.toUpperCase()];
};

/**
 * Get all active countries
 */
export const getActiveCountries = (): CountryConfig[] => {
  return Object.values(COUNTRIES).filter(country => country.isActive);
};

/**
 * Get country by name (case-insensitive)
 */
export const getCountryByName = (name: string): CountryConfig | undefined => {
  const searchName = name.toLowerCase().trim();
  return Object.values(COUNTRIES).find(
    country => country.name.toLowerCase() === searchName,
  );
};

/**
 * Get countries by currency code
 */
export const getCountriesByCurrency = (
  currencyCode: string,
): CountryConfig[] => {
  return Object.values(COUNTRIES).filter(
    country => country.currencyCode === currencyCode.toUpperCase(),
  );
};

// Type guard to check if a value is a valid country code
export const isCountryCode = (code: string): code is keyof typeof COUNTRIES => {
  return isValidCountryCode(code);
};

// Export the type for the country codes
export type CountryCode = keyof typeof COUNTRIES;
